### PR TITLE
Update Hero section

### PR DESCRIPTION
**Pull request by saenuruki**
## Wireframe
Screenshot 2024-05-08 at 20 07 48

## Output
Screenshot 2024-05-08 at 20 09 57

### CODE REVIEW

**Review by Tch4lla — COMMENTED** [review]
How do you feel about the faces being covered by the logo?

**Comment by Jonnie-Dev** [comment]
How about the logo being beside the MeltingHack text on the header

**Comment by Jonnie-Dev** [comment]
Also the hero background picture seem blury, maybe due to the image qualtity

**Comment by saenuruki** [comment]
> How do you feel about the faces being covered by the logo?
Since this is a background image, I don't think it's necessary to worry too much about the faces being covered. 
However, it seems like it would be better without the image, so I'll remove it!

> How about the logo being beside the MeltingHack text on the header
That's also good idea! Let me try it!

**Comment by saenuruki** [comment]
> Also the hero background picture seem blury, maybe due to the image qualtity

Hum... Good point..
I think it's possible to improve the image quality. 
However, since a low-loading Hero image can cause user frustration, we need to find the right image size.

**Comment by saenuruki** [comment]
Updated!!
Screenshot 2024-05-08 at 21 45 28

**Review by Morizuq — APPROVED** [review]

**Comment by Tch4lla** [comment]
Its definitely an improvement. I feel that the way the text is on top of the picture, it is not easy to read. My eyes need to do a bit more work to focus on the actual words 

image

**Comment by Tch4lla** [comment]
In all of the wireframe examples, the websites don't overlay their message over their  pictures directly. Perhaps we could follow a similar pattern 
image

image

image

**Comment by Jonnie-Dev** [comment]
@Tch4lla I increased the overlay opacity of the image while working on the FAQ section, will push once all these are out of the line

**Comment by Tch4lla** [comment]
@Jonnie-Dev let's make that a separate commit on this branch as it will be easier to keep track of changes.

**Comment by Jonnie-Dev** [comment]
I'm guessing only Sae will be able to add a new commit, or is possible to add my commit to this PR?

**Comment by Jonnie-Dev** [comment]
Alright will work on that first thing tomorrow morning, it's night here already.

**Pull request merged**
