### PR TITLE
Upload photos for Core members

### PR DESCRIPTION
**Pull request by saenuruki**

### CODE REVIEW

**Comment by Tch4lla** [comment]
To confirm @saenuruki , this PR is just for the team members photos. That means in another branch, we need to add the photos onto the component correct?

**Review by Tch4lla — COMMENTED** [review]
LGTM

**Comment by Morizuq** [comment]
> To confirm @saenuruki , this PR is just for the team members photos. That means in another branch, we need to add the photos onto the component correct?

Yes! The image paths along with other placeholders would have to be updated in the team data

**Review by Morizuq — APPROVED** [review]

**Comment by saenuruki** [comment]
Hey @Tch4lla @Morizuq 
Thank you for reviewing this PR!
Yes, this PR is just the purpose for uploading image data!
And the next branch we can edit the team section!

**Comment by saenuruki** [comment]
Let me merge it!

**Pull request merged**
